# Generated by Django 4.1.7 on 2023-03-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_App', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Timing',
            new_name='Date',
        ),
    ]
