# Generated by Django 4.1.7 on 2023-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_App', '0005_rename_timing_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_details',
            name='Treatment',
        ),
        migrations.AddField(
            model_name='booking',
            name='Treatment',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
